
text = """
app/pages/admin/statistics/stats/SalesSummaryCards.vue
app/pages/admin/statistics/stats/SalesHeader.vue
app/pages/admin/statistics/stats/SalesTable.vue
app/pages/admin/statistics/stats/SalesChart.vue
app/pages/admin/statistics/stats/SalesSummaryCard.vue
app/pages/admin/statistics/stats/SalesFilters.vue
app/pages/admin/statistics/stats/SalesExport.vue
app/pages/admin/statistics/stats/SalesAdvancedAnalytics.vue
app/pages/admin/statistics/stats/SalesRevenueTrends.vue
app/pages/admin/statistics/stats/SalesCustomerSegments.vue
app/pages/admin/statistics/stats/SalesTopProducts.vue
app/pages/admin/statistics/visits/SummaryCard.vue
app/pages/admin/statistics/visits/VisitsSummaryCards.vue
app/pages/admin/statistics/visits/VisitsHeader.vue
app/pages/admin/product-management/products/new/TierPricingTable.vue
app/pages/admin/shipping-methods/FlatRatePricing.vue
app/pages/admin/shipping-methods/UsageStatistics.vue
app/pages/admin/shipping-methods/driver-tracking/index.vue
app/pages/admin/shipping-methods/SectionCard.vue
app/pages/admin/roles.vue
app/pages/admin/developer/media-debug.vue
app/pages/admin/developer/system-performance.vue
app/pages/admin/developer/performance-analyzer.vue
app/pages/admin/developer/package-manager.vue
app/pages/admin/developer/devops.vue
app/pages/admin/developer/cicd-pipeline.vue
app/pages/admin/developer/log-viewer.vue
app/pages/admin/developer/git-manager.vue
app/pages/admin/developer/docker-manager.vue
app/pages/admin/developer/database-status.vue
app/pages/admin/developer/digikala-import/index.vue
app/pages/admin/developer/digikala-import/details/[importId].vue
app/pages/admin/developer/security-scanner.vue
app/pages/admin/developer/system-test.vue
app/pages/admin/developer/environment-manager.vue
app/pages/admin/developer/wordpress-migration/index.vue
app/pages/admin/developer/database-explorer.vue
app/pages/admin/developer/kubernetes-manager.vue
app/pages/admin/developer/test-api.vue
app/pages/admin/developer/performance-optimizer.vue
app/pages/admin/developer/deployment-manager.vue
app/pages/admin/developer/monitoring-dashboard.vue
app/pages/admin/developer/code-editor.vue
app/pages/admin/developer/api.vue
app/pages/admin/developer/test-connection.vue
app/pages/admin/developer/api-testing.vue
app/pages/admin/developer/backup-manager.vue
app/pages/admin/post-management/TitleInserter.vue
app/pages/admin/post-management/TitleSuggestionDropdown.vue
app/pages/admin/post-management/add-post/SeoTab.vue
app/pages/admin/attributes.vue
app/pages/admin/content/footer-management/componets/Footer.vue
app/pages/admin/content/footer-management/componets/ItemsSelectionModal.vue
app/pages/admin/content/footer-management/componets/FooterPreview.vue
app/pages/admin/content/footer-management/componets/FooterWidgets/FooterWidgetWorkingHours.vue
app/pages/admin/content/footer-management/componets/FooterWidgets/FooterWidgetSocial.vue
app/pages/admin/content/footer-management/componets/FooterWidgets/FooterWidgetLogo.vue
app/pages/admin/content/footer-management/componets/FooterWidgets/FooterWidgetTrust.vue
app/pages/admin/content/footer-management/componets/FooterWidgets/FooterWidgetContact.vue
app/pages/admin/content/footer-management/componets/FooterWidgets/FooterWidgetNewsletter.vue
app/pages/admin/content/footer-management/componets/FooterWidgets/FooterWidgetCustom.vue
app/pages/admin/content/footer-management/componets/FooterWidgets/FooterWidgetCopyright.vue
app/pages/admin/content/footer-management/componets/FooterWidgets/FooterWidgetAddress.vue
app/pages/admin/content/footer-management/componets/FooterWidgets/FooterWidgetAbout.vue
app/pages/admin/content/footer-management/componets/FooterWidgets/FooterWidgetLinks.vue
app/pages/admin/content/footer-management/componets/FooterWidgets/FooterWidgetMap.vue
app/pages/admin/content/footer-management/componets/ItemSettingsDrawer.vue
app/pages/admin/content/footer-management/create/FooterSettingsForm.vue
app/pages/admin/content/footer-management/create/ItemsSelectionModal.vue
app/pages/admin/content/footer-management/create/FooterPreview.vue
app/pages/admin/content/footer-management/create/PageHeader.vue
app/pages/admin/content/footer-management/create/FooterSettingsSidebar.vue
app/pages/admin/content/footer-management/create/FormContainer.vue
app/pages/admin/content/header-management/componets/HeaderWidgetAuth.vue
app/pages/admin/content/header-management/componets/HeaderWidgetSearch.vue
app/pages/admin/content/header-management/componets/SiteTopBar.vue
app/pages/admin/content/header-management/componets/HeaderWidgetMenu.vue
app/pages/admin/content/header-management/componets/HeaderWidgetCart.vue
app/pages/admin/content/header-management/componets/HeaderWidgetImage.vue
app/pages/admin/content/header-management/componets/HeaderWidgetLanguage.vue
app/pages/admin/content/header-management/componets/HeaderWidgetLogo.vue
app/pages/admin/content/header-management/componets/HeaderWidgetSocial.vue
app/pages/admin/content/header-management/componets/HeaderWidgetNotification.vue
app/pages/admin/content/header-management/componets/HeaderWidgetCustomBox.vue
app/pages/admin/content/header-management/componets/HeaderWidgetCurrency.vue
app/pages/admin/content/header-management/componets/Header.vue
app/pages/admin/content/header-management/create/HeaderPreview.vue
app/pages/admin/content/header-management/create/HeaderSettingsForm.vue
app/pages/admin/content/header-management/create/ItemsSelectionModal.vue
app/pages/admin/content/header-management/create/PageHeader.vue
app/pages/admin/content/header-management/create/ItemSettingsDrawer.vue
app/pages/admin/content/header-management/create/FormContainer.vue
app/pages/admin/content/header-management/create/HeaderSettingsSidebar.vue
app/pages/admin/content/mobile-app-navigation-management/template/Contact.vue
app/pages/admin/content/mobile-app-navigation-management/template/Home.vue
app/pages/admin/content/mobile-app-navigation-management/template/Login.vue
app/pages/admin/content/mobile-app-navigation-management/template/DarkMode.vue
app/pages/admin/content/mobile-app-navigation-management/template/Categories.vue
app/pages/admin/content/mobile-app-navigation-management/template/Cart.vue
app/pages/admin/content/banners/ProductCarousel/create/ProductCarouselItem.vue
app/pages/admin/content/banners/ProductCarousel/create/CarouselNavigation.vue
app/pages/admin/content/banners/ProductCarousel/create/CarouselIndicators.vue
app/pages/admin/content/banners/ProductCarousel/create/ProductCarousel.vue
app/pages/admin/content/banners/ProductCarousel/create/CarouselControls.vue
app/pages/admin/content/mobile-app-header-management/templates/banner-template.vue
app/pages/admin/content/mobile-app-header-management/templates/index.vue
app/pages/admin/content/mobile-app-header-management/templates/classic-template.vue
app/pages/admin/content/mobile-app-header-management/templates/minimal-template.vue
app/pages/admin/finance/installment-payments/InstallmentAdvancedAnalytics.vue
app/pages/admin/finance/installment-payments/InstallmentProducts.vue
app/pages/admin/finance/installment-payments/InstallmentTopProducts.vue
app/pages/admin/finance/installment-payments/InstallmentHeader.vue
app/pages/admin/finance/installment-payments/InstallmentChart.vue
app/pages/admin/finance/installment-payments/InstallmentLogs.vue
app/pages/admin/finance/installment-payments/InstallmentCreditSettings.vue
app/pages/admin/finance/installment-payments/InstallmentGeography.vue
app/pages/admin/finance/installment-payments/InstallmentExport.vue
app/pages/admin/finance/installment-payments/InstallmentValidationMethods.vue
app/pages/admin/finance/installment-payments/InstallmentFilters.vue
app/pages/admin/finance/installment-payments/InstallmentCustomers.vue
app/pages/admin/finance/installment-payments/InstallmentSettings.vue
app/pages/admin/finance/installment-payments/InstallmentTrends.vue
app/pages/admin/finance/installment-payments/InstallmentTable.vue
app/pages/admin/finance/installment-payments/InstallmentSummaryStats.vue
app/pages/admin/finance/installment-payments/InstallmentStatus.vue
app/pages/admin/finance/installment-payments/InstallmentCreditCheck.vue
app/pages/admin/finance/accounting/reporting/ConnectionStatusReport.vue
app/pages/admin/finance/accounting/reporting/SyncErrorsReport.vue
app/pages/admin/finance/accounting/reporting/SyncedTransactionsReport.vue
app/pages/admin/finance/accounting/reporting/ConnectionActivityLogs.vue
app/pages/admin/finance/accounting/reporting/ConnectionPerformanceMonitoring.vue
app/pages/admin/finance/accounting/AccountingHeader.vue
app/pages/admin/finance/accounting/AccountCodesManagement.vue
app/pages/admin/finance/accounting/transaction/DualTransactionManagement.vue
app/pages/admin/finance/accounting/transaction/ReturnAutoRegistration.vue
app/pages/admin/finance/accounting/transaction/DiscountAutoRegistration.vue
app/pages/admin/finance/accounting/transaction/PaymentAutoRegistration.vue
app/pages/admin/finance/accounting/transaction/InvoiceAutoRegistration.vue
app/pages/admin/finance/accounting/PurchaseAccounts.vue
app/pages/admin/finance/accounting/SalesAccounts.vue
app/pages/admin/finance/accounting/AutoAccountMapping.vue
app/pages/admin/finance/accounting/DataSynchronization.vue
app/pages/admin/finance/accounting/settings/ApiKeyManagement.vue
app/pages/admin/finance/accounting/settings/BackupSettings.vue
app/pages/admin/finance/accounting/settings/SecuritySettings.vue
app/pages/admin/finance/accounting/settings/EncryptionSettings.vue
app/pages/admin/finance/accounting/settings/PermissionManagement.vue
app/pages/admin/finance/accounting/BankAccounts.vue
app/pages/admin/finance/accounting/errors/AutoRecovery.vue
app/pages/admin/finance/accounting/errors/ErrorTroubleshooting.vue
app/pages/admin/finance/accounting/errors/ErrorAlerts.vue
app/pages/admin/finance/accounting/errors/ErrorReports.vue
app/pages/admin/finance/accounting/errors/AutoErrorDetection.vue
app/pages/admin/finance/accounting/ReportingAndMonitoring.vue
app/pages/admin/finance/accounting/ErrorManagement.vue
app/pages/admin/finance/tax/TaxReports.vue
app/pages/admin/finance/tax/TaxExemptions.vue
app/pages/admin/finance/tax/TaxTrendChart.vue
app/pages/admin/finance/tax/TaxHeader.vue
app/pages/admin/finance/tax/TaxCalculationTest.vue
app/pages/admin/finance/tax/TaxDashboard.vue
app/pages/admin/finance/tax/TaxCalculationSettings.vue
app/pages/admin/finance/tax/TaxComparison.vue
app/pages/admin/finance/tax/TaxCalculator.vue
app/pages/admin/finance/tax/TaxRegionalRates.vue
app/pages/admin/finance/tax/TaxInvoices.vue
app/pages/admin/finance/tax/TaxAdvancedReports.vue
app/pages/admin/finance/tax/TaxRatesManagement.vue
app/pages/admin/finance/Payments/PaymentsLogs.vue
app/pages/admin/finance/Payments/PaymentsAdvancedAnalytics.vue
app/pages/admin/finance/Payments/PaymentsChart.vue
app/pages/admin/finance/Payments/PaymentsGeography.vue
app/pages/admin/finance/Payments/PaymentsStatus.vue
app/pages/admin/finance/Payments/PaymentsAmounts.vue
app/pages/admin/finance/Payments/PaymentsMethods.vue
app/pages/admin/finance/Payments/PaymentsGatewaySettings.vue
app/pages/admin/finance/Payments/PaymentsFilters.vue
app/pages/admin/finance/Payments/PaymentsTable.vue
app/pages/admin/finance/Payments/PaymentsTimeAnalysis.vue
app/pages/admin/finance/Payments/PaymentsSummaryStats.vue
app/pages/admin/finance/Payments/PaymentsTopProducts.vue
app/pages/admin/finance/Payments/PaymentsHeader.vue
app/pages/admin/finance/Payments/PaymentsCustomers.vue
app/pages/admin/finance/Payments/PaymentsExport.vue
app/pages/admin/finance/Payments/PaymentsTrends.vue
app/pages/admin/transactions/order-surveys/NotificationSystem.vue
app/pages/admin/transactions/order-surveys/OrderInfoHeader.vue
app/pages/admin/transactions/order-surveys/NotificationBanner.vue
app/pages/admin/transactions/order-surveys/IntegrationManager.vue
app/pages/admin/transactions/order-surveys/ThankYouMessage.vue
app/pages/admin/transactions/order-surveys/FreeTextComments.vue
app/pages/admin/transactions/order-surveys/SurveyReports.vue
app/pages/admin/transactions/order-surveys/DetailedRating.vue
app/pages/admin/transactions/order-surveys/InteractiveStarRating.vue
app/pages/admin/transactions/order-surveys/RatingStats.vue
app/pages/admin/transactions/order-surveys/FileUploadManager.vue
app/pages/admin/transactions/order-surveys/PerformanceOptimizer.vue
app/pages/admin/transactions/order-surveys/SpecializedQuestions.vue
app/pages/admin/transactions/order-surveys/ProgressBar.vue
app/pages/admin/transactions/order-surveys/OptionalSection.vue
app/pages/admin/transactions/order-surveys/RewardSection.vue
app/pages/admin/transactions/order-surveys/DataAnalytics.vue
app/pages/admin/transactions/order-surveys/SubmitSection.vue
app/pages/admin/transactions/order-surveys/OverallExperienceRating.vue
app/pages/admin/transactions/order-surveys/SurveyReviewManagement.vue
app/pages/admin/transactions/order-surveys/BackupRestore.vue
app/pages/admin/transactions/order-surveys/ValidationPreview.vue
app/pages/admin/transactions/order-surveys/SecurityManager.vue
app/pages/admin/transactions/order-surveys/SurveyStatsDashboard.vue
app/pages/admin/transactions/order-surveys2/ErrorDetailTable.vue
app/pages/admin/transactions/order-surveys2/ProductRatingChart.vue
app/pages/admin/transactions/order-surveys2/MonthlyReportChart.vue
app/pages/admin/transactions/order-surveys2/response/ResponseList.vue
app/pages/admin/transactions/order-surveys2/response/ResponseAnalysis.vue
app/pages/admin/transactions/order-surveys2/BulkOrderManager.vue
app/pages/admin/transactions/order-surveys2/sending/ManualSending.vue
app/pages/admin/transactions/order-surveys2/sending/AutomaticSending.vue
app/pages/admin/transactions/order-surveys2/DailyReportChart.vue
app/pages/admin/transactions/order-surveys2/SMSManagement.vue
app/pages/admin/transactions/order-surveys2/ResponsePieChart.vue
app/pages/admin/transactions/order-surveys2/ErrorTrendChart.vue
app/pages/admin/transactions/order-surveys2/AdvancedAnalytics.vue
app/pages/admin/transactions/order-surveys2/OrderSurveyResponses.vue
app/pages/admin/transactions/order-surveys2/AdvancedReports.vue
app/pages/admin/transactions/order-surveys2/StatsDashboard.vue
app/pages/admin/transactions/order-surveys2/NotificationsSettings.vue
app/pages/admin/transactions/order-surveys2/UIPersonalization.vue
app/pages/admin/transactions/order-surveys2/GenderResponseChart.vue
app/pages/admin/transactions/order-surveys2/OrderListTable.vue
app/pages/admin/transactions/order-surveys2/GenderDistributionChart.vue
app/pages/admin/transactions/order-surveys2/TrendChart.vue
app/pages/admin/transactions/order-surveys2/ProductPerformanceChart.vue
app/pages/admin/transactions/order-surveys2/AccessControl.vue
app/pages/admin/transactions/order-surveys2/ErrorTypeChart.vue
app/pages/admin/transactions/order-surveys2/ProductRankingTable.vue
app/pages/admin/transactions/order-surveys2/errors/ErrorAnalysis.vue
app/pages/admin/transactions/order-surveys2/errors/ErrorManagement.vue
app/pages/admin/transactions/order-surveys2/SMSSettings.vue
app/pages/admin/transactions/order-surveys2/SurveyTemplates.vue
app/pages/admin/transactions/order-surveys2/WeeklyReportChart.vue
app/pages/admin/transactions/order-surveys2/templates/SMSTemplates.vue
app/pages/admin/transactions/order-surveys2/GenderDetailTable.vue
app/pages/admin/transactions/order-surveys2/BackupExport.vue
app/pages/admin/transactions/orders/refunded/RefundedReports.vue
app/pages/admin/transactions/orders/refunded/RefundedOrdersTable.vue
app/pages/admin/transactions/orders/refunded/RefundedDashboard.vue
app/pages/admin/transactions/orders/in-progress/old-in-progress.vue
app/pages/admin/transactions/orders/in-progress/InProgressReports.vue
app/pages/admin/transactions/orders/in-progress/InProgressDashboard.vue
app/pages/admin/transactions/orders/in-progress/InProgressOrdersTable.vue
app/pages/admin/transactions/orders/shipped/ShippedDashboard.vue
app/pages/admin/transactions/orders/shipped/ShippedReports.vue
app/pages/admin/transactions/orders/shipped/ShippedAdvancedFilters.vue
app/pages/admin/transactions/orders/shipped/ShippedOrdersTable.vue
app/pages/admin/transactions/orders/OrderDetailModal.vue
app/pages/admin/transactions/orders/CreateOrderModal.vue
app/pages/admin/transactions/orders/QuickActionsModal.vue
app/pages/admin/transactions/orders/OrderTable.vue
app/pages/admin/transactions/orders/returned/ReturnedDashboard.vue
app/pages/admin/transactions/orders/returned/ReturnedReports.vue
app/pages/admin/transactions/orders/returned/ReturnedOrdersTable.vue
app/pages/admin/transactions/orders/processing/old-processing.vue
app/pages/admin/transactions/orders/processing/ProcessingOrdersTable.vue
app/pages/admin/transactions/orders/processing/ProcessingDashboard.vue
app/pages/admin/transactions/orders/processing/ProcessingReports.vue
app/pages/admin/transactions/orders/OrderEditModal.vue
app/pages/admin/transactions/orders/OrderFilters.vue
app/pages/admin/support-management/statistics/call-archive.vue
app/pages/admin/support-management/statistics/call-statistics.vue
app/pages/admin/support-management/statistics/customer-satisfaction.vue
app/pages/admin/users/UserActivityTab.vue
app/pages/admin/users/UserStockAlertsTable.vue
app/pages/admin/users/UserWishlistSection.vue
app/pages/admin/users/ExportUsersBtn.vue
app/pages/admin/users/UserDiscountAlertsTable.vue
app/pages/admin/users/UserProfileTab.vue
app/pages/admin/users/UserMessagesSection.vue
app/pages/admin/users/UserActivityTable.vue
app/pages/admin/users/UserStockAlertsSection.vue
app/pages/admin/users/UserAdminActionsTab.vue
app/pages/admin/users/UserFilterBar.vue
app/pages/admin/users/AdminRegisterModal.vue
app/pages/admin/users/UserDiscountAlertSection.vue
app/pages/admin/users/UserSecurityTab.vue
app/pages/admin/users/UserWalletTable.vue
app/pages/admin/users/UserFailedAttemptsSection.vue
app/pages/admin/users/UserStockAlertSection.vue
app/pages/admin/users/UserDetailDrawer.vue
app/pages/admin/users/NewUserModal.vue
app/pages/admin/users/UserOrdersTable.vue
app/pages/admin/users/UserSuccessfulLoginsSection.vue
app/pages/admin/users/UserBankInfoSection.vue
app/pages/admin/users/UserBehaviorTab.vue
app/pages/admin/users/UserTable.vue
app/pages/admin/users/UserActiveSessionsSection.vue
app/pages/admin/users/user-rating-system/RankLevelsConfig.vue
app/pages/admin/users/user-rating-system/RankBarChart.vue
app/pages/admin/users/user-rating-system/RankCriteriaConfig.vue
app/pages/admin/users/UserNextCartTable.vue
app/pages/admin/users/NewUserBtn.vue
app/pages/admin/users/UserNextCartSection.vue
app/pages/admin/users/UserAddressesTable.vue
app/pages/admin/users/UserBehaviorTable.vue
app/pages/admin/users/UserCartTable.vue
app/pages/admin/users/UserWalletSection.vue
app/pages/admin/users/UserMessagesTable.vue
app/pages/admin/users/UserSecurityTable.vue
app/pages/admin/users/UserCartSection.vue
app/pages/admin/users/UserDiscountAlertsSection.vue
app/pages/admin/users/UserRecentViewsSection.vue
app/pages/admin/users/UserStatsCards.vue
app/pages/admin/users/UserWishlistTable.vue
app/pages/admin/users/UserBankInfoTable.vue
app/pages/admin/users/UserOrdersTab.vue
app/pages/admin/media-management/video-compression/VideoCompressionResults.vue
app/pages/admin/media-management/video-compression/VideoCompressionSettings.vue
app/pages/admin/media-management/video-compression/VideoMonitoring.vue
app/pages/admin/media-management/video-compression/VideoPreview.vue
app/pages/admin/media-management/video-compression/VideoManualCompression.vue
app/pages/admin/media-management/video-compression/VideoCompressionQueue.vue
"""

components = """
app/pages/admin/marketing/recommender/components/SentimentEmotionAnalysis.vue
app/pages/admin/marketing/recommender/components/AdvancedBehaviorAnalytics.vue
app/pages/admin/marketing/recommender/components/AdvancedUX.vue
app/pages/admin/marketing/recommender/components/MachineLearningAlgorithms.vue
app/pages/admin/marketing/recommender/components/PersonalizationSettings.vue
app/pages/admin/marketing/recommender/components/DataQualityManagement.vue
app/pages/admin/marketing/recommender/components/SmartRecommendations.vue
app/pages/admin/marketing/recommender/components/ImageVideoRecognition.vue
app/pages/admin/marketing/recommender/components/NaturalLanguageProcessing.vue
app/pages/admin/marketing/recommender/components/OptimizationPerformance.vue
app/pages/admin/marketing/recommender/components/PerformanceAnalysis.vue
app/pages/admin/marketing/recommender/components/PerformanceOptimization.vue
app/pages/admin/marketing/recommender/components/FraudDetectionSecurity.vue
app/pages/admin/marketing/recommender/components/UserBehaviorAnalysis.vue
app/pages/admin/marketing/recommender/components/Gamification.vue
app/pages/admin/marketing/recommender/components/ExternalIntegration.vue
app/pages/admin/marketing/recommender/components/DeepLearningNeuralNetworks.vue
app/pages/admin/marketing/recommender/components/ReportingMonitoring.vue
app/pages/admin/marketing/recommender/components/EthicsTransparency.vue
app/pages/admin/marketing/recommender/components/PredictionAdvancedAnalytics.vue
app/pages/admin/marketing/discounts/components/CouponDetails.vue
app/pages/admin/marketing/discounts/components/CouponList.vue
app/pages/admin/marketing/discounts/components/AdvancedSettings.vue
app/pages/admin/marketing/discounts/components/AdvancedReports.vue
app/pages/admin/marketing/discounts/components/BudgetManagement.vue
app/pages/admin/marketing/discounts/components/SystemIntegration.vue
app/pages/admin/marketing/discounts/components/AdvancedTemplates.vue
app/pages/admin/marketing/discounts/components/NotificationManagement.vue
app/pages/admin/marketing/discounts/components/RuleManagement.vue
app/pages/admin/marketing/discounts/components/ContentManagement.vue
app/pages/admin/settings/components/SettingsMenu.vue
app/pages/admin/content/menu-management/components/MenuTreeNode.vue
app/pages/admin/content/banners/triplebanner/edit/components/DeviceTabs.vue
app/pages/admin/content/banners/triplebanner/create/components/DeviceTabs.vue
app/pages/admin/content/banners/quadbanner/edit/components/DeviceTabs.vue
app/pages/admin/content/banners/quadbanner/create/components/DeviceTabs.vue
app/pages/admin/content/banners/SingleSliderSide/edit/components/DeviceTabs.vue
app/pages/admin/content/banners/SingleSliderSide/create/components/DeviceTabs.vue
app/pages/admin/content/banners/ProductCarousel/create/components/CategorySelector.vue
app/pages/admin/content/banners/ProductCarousel/create/components/ProductCarouselSettings.vue
app/pages/admin/content/banners/ProductCarousel/create/components/ProductCarouselPreview.vue
app/pages/admin/content/banners/MainSliderSideBanner/edit/components/DeviceTabs.vue
app/pages/admin/content/banners/MainSliderSideBanner/create/components/DeviceTabs.vue
app/pages/admin/content/banners/DoubleBanner/edit/components/DeviceTabs.vue
app/pages/admin/content/banners/DoubleBanner/create/components/DeviceTabs.vue
app/pages/admin/content/banners/CategoryBox/edit/components/CategoryBoxSettings.vue
app/pages/admin/content/banners/CategoryBox/create/components/CategoryBoxSettings.vue
app/pages/admin/content/banners/pentabanner/edit/components/DeviceTabs.vue
app/pages/admin/content/banners/pentabanner/create/components/DeviceTabs.vue
app/pages/admin/content/banners/FullBanner/edit/components/DeviceTabs.vue
app/pages/admin/content/banners/FullBanner/create/components/DeviceTabs.vue
app/pages/admin/finance/accounting/components/SecurityManagement.vue
app/pages/admin/finance/accounting/components/testing/DataValidation.vue
app/pages/admin/finance/accounting/components/testing/ConnectionTesting.vue
app/pages/admin/finance/accounting/components/testing/PerformanceTesting.vue
app/pages/admin/finance/accounting/components/testing/TestingValidation.vue
app/pages/admin/finance/accounting/components/testing/TestReports.vue
app/pages/admin/finance/accounting/components/support/SupportVideos.vue
app/pages/admin/finance/accounting/components/support/SupportGuide.vue
app/pages/admin/finance/accounting/components/support/SupportAPIDocs.vue
app/pages/admin/finance/accounting/components/support/SupportFAQ.vue
app/pages/admin/finance/accounting/components/support/SupportTechnical.vue
app/pages/admin/finance/accounting/components/DashboardStatistics.vue
app/pages/admin/finance/accounting/components/SupportHelp.vue
app/pages/admin/finance/accounting/components/ui/UIFilters.vue
app/pages/admin/finance/accounting/components/ui/UserInterface.vue
app/pages/admin/finance/accounting/components/ui/UICharts.vue
app/pages/admin/finance/accounting/components/ui/UISearch.vue
app/pages/admin/finance/accounting/components/ui/UIStatus.vue
app/pages/admin/finance/accounting/components/ui/UIDesign.vue
app/pages/admin/finance/accounting/components/version/VersionRollback.vue
app/pages/admin/finance/accounting/components/version/VersionManagement.vue
app/pages/admin/finance/accounting/components/version/VersionList.vue
app/pages/admin/finance/accounting/components/version/VersionCompare.vue
app/pages/admin/finance/accounting/components/version/VersionArchive.vue
app/pages/admin/finance/accounting/components/security/ApiKeyManagement.vue
app/pages/admin/finance/accounting/components/security/SecuritySettings.vue
app/pages/admin/finance/accounting/components/security/EncryptionSettings.vue
app/pages/admin/finance/accounting/components/security/PermissionManagement.vue
app/pages/admin/finance/accounting/components/data/DataManagement.vue
app/pages/admin/finance/accounting/components/data/DataArchive.vue
app/pages/admin/finance/accounting/components/data/DataCleanup.vue
app/pages/admin/finance/accounting/components/data/DataMigration.vue
app/pages/admin/finance/accounting/components/data/BackupRestore.vue
app/pages/admin/finance/wallet/components/TaxManagement.vue
app/pages/admin/finance/wallet/components/TransactionManagement.vue
app/pages/admin/finance/wallet/components/AnalyticsDashboard.vue
app/pages/admin/finance/wallet/components/AdvancedReports.vue
app/pages/admin/finance/wallet/components/AccountingIntegration.vue
app/pages/admin/finance/wallet/components/WithdrawalManagement.vue
app/pages/admin/finance/wallet/components/WalletBalanceManagement.vue
app/pages/admin/finance/wallet/components/ApiWebhookManagement.vue
app/pages/admin/finance/wallet/components/AccountingErrorManagement.vue
app/pages/admin/finance/wallet/components/FinancialAnalytics.vue
app/pages/admin/finance/wallet/components/DocumentationSupport.vue
app/pages/admin/finance/wallet/components/AuthenticationSecurity.vue
app/pages/admin/finance/wallet/components/WalletSettings.vue
app/pages/admin/finance/wallet/components/UserManagement.vue
app/pages/admin/finance/wallet/components/SecurityLogs.vue
app/pages/admin/finance/wallet/components/InternalControls.vue
app/pages/admin/finance/wallet/components/ManualWalletManagement.vue
app/pages/admin/finance/wallet/components/NotificationManagement.vue
app/pages/admin/finance/wallet/components/BackupManagement.vue
app/pages/admin/finance/wallet/components/ChargeManagement.vue
app/pages/admin/finance/wallet/components/ErrorManagement.vue
app/pages/admin/finance/wallet/components/ExternalIntegrations.vue
app/pages/admin/finance/wallet/components/BankCardManagement.vue
app/pages/admin/finance/wallet/components/FinancialReports.vue
app/pages/admin/finance/giftcard/components/GiftCardPricingManager.vue
app/pages/admin/finance/giftcard/components/GiftCardSortableTable.vue
app/pages/admin/finance/giftcard/components/GiftCardFilters.vue
app/pages/admin/finance/giftcard/components/GiftCardTemplateManager.vue
app/pages/admin/finance/giftcard/components/GiftCardCreateModal.vue
app/pages/admin/finance/giftcard/components/GiftCardTransactionDetailsModal.vue
app/pages/admin/finance/giftcard/components/GiftCardAdvancedFeatures.vue
app/pages/admin/finance/giftcard/components/GiftCardDetails.vue
app/pages/admin/finance/giftcard/components/GiftCardUserCreateModal.vue
app/pages/admin/finance/giftcard/components/GiftCardThemeCreateModal.vue
app/pages/admin/finance/giftcard/components/GiftCardNotificationCenter.vue
app/pages/admin/finance/giftcard/components/GiftCardRefundDetailsModal.vue
app/pages/admin/finance/giftcard/components/GiftCardMessageCreateModal.vue
app/pages/admin/finance/giftcard/components/GiftCardThemesManager.vue
app/pages/admin/finance/giftcard/components/GiftCardPerformanceOptimization.vue
app/pages/admin/finance/giftcard/components/GiftCardRefundManager.vue
app/pages/admin/finance/giftcard/components/GiftCardReports.vue
app/pages/admin/finance/giftcard/components/GiftCardTypeEditModal.vue
app/pages/admin/finance/giftcard/components/GiftCardTransactionCreateModal.vue
app/pages/admin/finance/giftcard/components/GiftCardOccasionCreateModal.vue
app/pages/admin/finance/giftcard/components/GiftCardSearchAndFilter.vue
app/pages/admin/finance/giftcard/components/GiftCardQuickActions.vue
app/pages/admin/finance/giftcard/components/GiftCardFinancialManagement.vue
app/pages/admin/finance/giftcard/components/GiftCardNotificationManager.vue
app/pages/admin/finance/giftcard/components/GiftCardThemeEditModal.vue
app/pages/admin/finance/giftcard/components/GiftCardLifecycleManagement.vue
app/pages/admin/finance/giftcard/components/GiftCardSavedFilters.vue
app/pages/admin/finance/giftcard/components/GiftCardTypesManager.vue
app/pages/admin/finance/giftcard/components/GiftCardSystemSettings.vue
app/pages/admin/finance/giftcard/components/GiftCardRecentActivity.vue
app/pages/admin/finance/giftcard/components/GiftCardSecuritySettings.vue
app/pages/admin/finance/giftcard/components/GiftCardBulkCreateModal.vue
app/pages/admin/finance/giftcard/components/GiftCardNotificationSettings.vue
app/pages/admin/finance/giftcard/components/GiftCardCustomerCreateModal.vue
app/pages/admin/finance/giftcard/components/GiftCardDetailsModal.vue
app/pages/admin/finance/giftcard/components/GiftCardRestrictionCreateModal.vue
app/pages/admin/finance/giftcard/components/GiftCardPhysicalManagement.vue
app/pages/admin/finance/giftcard/components/APIIntegrationGuide.vue
app/pages/admin/finance/giftcard/components/GiftCardQuickSearch.vue
app/pages/admin/finance/giftcard/components/GiftCardFinancialReports.vue
app/pages/admin/finance/giftcard/components/GiftCardMessageManager.vue
app/pages/admin/finance/giftcard/components/GiftCardPricing.vue
app/pages/admin/finance/giftcard/components/GiftCardRefundRequestModal.vue
app/pages/admin/finance/giftcard/components/GiftCardPrivacySettings.vue
app/pages/admin/finance/giftcard/components/GiftCardDiscountCreateModal.vue
app/pages/admin/finance/giftcard/components/GiftCardCustomerManager.vue
app/pages/admin/finance/giftcard/components/GiftCardPricingCreateModal.vue
app/pages/admin/finance/giftcard/components/GiftCardThemePreviewModal.vue
app/pages/admin/finance/giftcard/components/GiftCardCommissionCreateModal.vue
app/pages/admin/finance/giftcard/components/GiftCardAddressCreateModal.vue
app/pages/admin/finance/giftcard/components/GiftCardAnalyticsReports.vue
app/pages/admin/finance/giftcard/components/GiftCardTemplateEditModal.vue
app/pages/admin/finance/giftcard/components/GiftCardTypeCreateModal.vue
app/pages/admin/finance/giftcard/components/GiftCardAdvancedSearch.vue
app/pages/admin/finance/giftcard/components/GiftCardTransactions.vue
app/pages/admin/finance/giftcard/components/GiftCardNotificationTest.vue
app/pages/admin/finance/giftcard/components/GiftCardUserManager.vue
app/pages/admin/transactions/orders/edit/components/StatisticsReports.vue
app/pages/admin/transactions/orders/edit/components/OrderItems.vue
app/pages/admin/transactions/orders/edit/components/OrderStatus.vue
app/pages/admin/transactions/orders/edit/components/CustomerInfo.vue
app/pages/admin/transactions/orders/edit/components/OrderHeader.vue
app/pages/admin/transactions/orders/edit/components/WalletGiftCard.vue
app/pages/admin/transactions/orders/edit/components/SupportCommunication.vue
app/pages/admin/transactions/orders/edit/components/Invoice.vue
app/pages/admin/transactions/orders/edit/components/ShippingInfo.vue
app/pages/admin/transactions/orders/edit/components/TaxAccounting.vue
app/pages/admin/transactions/orders/edit/components/AdvancedLogistics.vue
app/pages/admin/transactions/orders/edit/components/OrderSummary.vue
app/pages/admin/transactions/orders/edit/components/PaymentGateways.vue
app/pages/admin/transactions/orders/edit/components/OrderFilters.vue
app/pages/admin/analytics/ci/competitor-profiles/components/CompetitorDetailModal.vue
app/pages/admin/analytics/ci/competitor-profiles/components/CompetitorFormModal.vue
app/pages/admin/analytics/ci/components/WebsiteTrafficMonitoring.vue
app/pages/admin/analytics/ci/components/SeoAnalysis.vue
app/pages/admin/analytics/ci/components/ContentAnalysis.vue
app/pages/admin/analytics/ci/components/DigitalAdvertising.vue
app/pages/admin/analytics/ci/components/SocialMediaMonitoring.vue
app/pages/admin/analytics/ci/components/OverviewDashboard.vue
app/pages/admin/support-management/live-chat/components/FileUploader.vue
app/pages/admin/support-management/live-chat/components/TicketManager.vue
app/pages/admin/support-management/live-chat/components/ChatBot.vue
app/pages/admin/support-management/live-chat/components/UserProfileModal.vue
app/pages/admin/support-management/live-chat/components/ChatNotification.vue
app/pages/admin/support-management/live-chat/components/VoiceRecorder.vue
app/pages/admin/support-management/live-chat/components/ChatAnalytics.vue
app/pages/admin/support-management/live-chat/components/ChatHeader.vue
app/pages/admin/support-management/live-chat/components/QuickReplies.vue
app/pages/admin/support-management/live-chat/components/ChatArea.vue
app/pages/admin/support-management/live-chat/components/TypingIndicator.vue
app/pages/admin/support-management/live-chat/components/ChatSettingsModal.vue
app/pages/admin/support-management/ai-chatbot/components/BotModal.vue
app/pages/admin/support-management/ai-chatbot/components/BotsTable.vue
app/pages/admin/support-management/ai-chatbot/components/StatsCards.vue
app/pages/admin/users/user-rating-system/components/TopUserBenefits.vue
app/pages/admin/users/user-rating-system/components/AlertSystem.vue
app/pages/admin/users/user-rating-system/components/ReviewQualitySystem.vue
app/pages/admin/users/user-rating-system/components/ManualScoring.vue
app/pages/admin/users/user-rating-system/components/ScenarioManagementSystem.vue
app/pages/admin/users/user-rating-system/components/SystemSettings.vue
app/pages/admin/users/user-rating-system/components/ReferralSystem.vue
app/pages/admin/users/user-rating-system/components/ReportsAndAnalytics.vue
app/pages/admin/users/user-rating-system/components/AutoScoringSystem.vue
app/pages/admin/users/user-rating-system/components/ReturnRateSystem.vue
app/pages/admin/users/user-rating-system/components/UserManagement.vue
app/pages/admin/users/user-rating-system/components/SetupAndTestingSystem.vue
app/pages/admin/users/user-rating-system/components/PurchaseContinuitySystem.vue
app/pages/admin/users/user-rating-system/components/AccountAgeSystem.vue
app/pages/admin/users/user-authentication/components/LoginHistory.vue
app/pages/admin/users/user-authentication/components/AuthSettings.vue
app/pages/admin/users/user-authentication/components/UserManagement.vue
app/pages/admin/media-management/image-compression/components/CompareModal.vue
app/pages/admin/media-management/image-compression/components/FileList.vue
app/pages/admin/media-management/image-compression/components/QueueProgress.vue
app/pages/admin/media-management/image-compression/components/CompressionSettingsForm.vue
"""

text_lines = [line.strip() for line in text.strip().split('\n') if line.strip()]
component_lines = [line.strip() for line in components.strip().split('\n') if line.strip()]

print(f"Files (Pages): {len(text_lines)}")
print(f"Components: {len(component_lines)}")
